"""
Pydantic V2 shared models for the Meridian VC Intelligence pipeline.

These models mirror the database/schema.sql table structures exactly,
including column names, types, and CHECK constraint enums.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Enums (matching schema CHECK constraints)
# ---------------------------------------------------------------------------

DataQuality = Literal["high", "medium", "low"]
CompanyStatus = Literal["Active", "Acquired", "IPO", "Shutdown", "Unknown"]
CompanyStage = Literal[
    "Pre-Seed", "Seed", "Early",
    "Series A", "Series B", "Series C", "Series D", "Series E",
    "Growth",
]
FounderRole = Literal["primary", "co-founder"]
EducationTier = Literal["Top-10", "Top-50", "Other"]
AgeConfidence = Literal["High", "Medium", "Low"]
EntityType = Literal["company", "founder", "vc_firm", "funding_round"]
SourceType = Literal["manual", "exa", "serper", "playwright", "sec_edgar", "user_submission"]
PipelineStatus = Literal["running", "completed", "failed", "partial"]

# Year range constants
MIN_FOUNDING_YEAR = 1900
MAX_FOUNDING_YEAR = 2030
MIN_BIRTH_YEAR = 1940
MAX_BIRTH_YEAR = 2010


# ---------------------------------------------------------------------------
# VCFirmRecord
# ---------------------------------------------------------------------------


class VCFirmRecord(BaseModel):
    """Maps to the `vc_firms` table."""

    id: str | None = None                              # UUID, generated by DB
    name: str = Field(..., min_length=1)
    slug: str = Field(..., min_length=1, pattern=r"^[a-z0-9-]+$")
    website: str | None = None
    description: str | None = None
    hq_city: str | None = None
    hq_country: str | None = None
    hq_region: str | None = None
    founded_year: int | None = None
    aum_usd: int | None = None
    fund_stage: list[str] = Field(default_factory=list)
    focus_sectors: list[str] = Field(default_factory=list)
    logo_url: str | None = None
    linkedin_url: str | None = None
    data_quality: DataQuality = "medium"
    created_at: datetime | None = None
    updated_at: datetime | None = None

    @field_validator("founded_year")
    @classmethod
    def validate_founded_year(cls, v: int | None) -> int | None:
        if v is not None and not (MIN_FOUNDING_YEAR <= v <= MAX_FOUNDING_YEAR):
            raise ValueError(
                f"founded_year must be between {MIN_FOUNDING_YEAR} and {MAX_FOUNDING_YEAR}, got {v}"
            )
        return v

    @field_validator("aum_usd")
    @classmethod
    def validate_aum_usd(cls, v: int | None) -> int | None:
        if v is not None and v < 0:
            raise ValueError("aum_usd must be non-negative")
        return v


# ---------------------------------------------------------------------------
# CompanyRecord
# ---------------------------------------------------------------------------


class CompanyRecord(BaseModel):
    """Maps to the `portfolio_companies` table."""

    id: str | None = None                              # UUID, generated by DB
    name: str = Field(..., min_length=1)
    slug: str = Field(..., min_length=1, pattern=r"^[a-z0-9-]+$")
    sector: str | None = None
    subsector: str | None = None
    founded_year: int | None = None
    city: str | None = None
    country: str | None = None
    region: str | None = None
    stage: CompanyStage | None = None
    status: CompanyStatus = "Active"
    status_detail: str | None = None
    website: str | None = None
    description: str | None = None
    total_raised_usd: int | None = None
    valuation_usd: int | None = None
    source_url: str | None = None
    last_verified: datetime | None = None
    data_quality: DataQuality = "medium"
    created_at: datetime | None = None
    updated_at: datetime | None = None

    @field_validator("founded_year")
    @classmethod
    def validate_founded_year(cls, v: int | None) -> int | None:
        if v is not None and not (MIN_FOUNDING_YEAR <= v <= MAX_FOUNDING_YEAR):
            raise ValueError(
                f"founded_year must be between {MIN_FOUNDING_YEAR} and {MAX_FOUNDING_YEAR}, got {v}"
            )
        return v

    @field_validator("total_raised_usd", "valuation_usd")
    @classmethod
    def validate_non_negative_amounts(cls, v: int | None) -> int | None:
        if v is not None and v < 0:
            raise ValueError("monetary amounts must be non-negative")
        return v


# ---------------------------------------------------------------------------
# FounderRecord
# ---------------------------------------------------------------------------


class FounderRecord(BaseModel):
    """Maps to the `founders` table."""

    id: str | None = None                              # UUID, generated by DB
    company_id: str = Field(..., description="UUID of the parent portfolio_companies row")
    full_name: str = Field(..., min_length=1)
    role: FounderRole = "primary"
    est_birth_year: int | None = None
    domain_exp_years: int | None = None
    prior_founder: bool = False
    education_tier: EducationTier | None = None
    university: str | None = None
    degree: str | None = None
    grad_year: int | None = None
    age_at_founding: int | None = None                # founded_year - est_birth_year
    current_age_2026: int | None = None               # 2026 - est_birth_year
    age_confidence: AgeConfidence = "Low"
    age_inference_method: str | None = None
    linkedin_url: str | None = None
    twitter_url: str | None = None
    nationality: str | None = None
    source_notes: str | None = None
    created_at: datetime | None = None

    @field_validator("est_birth_year")
    @classmethod
    def validate_birth_year(cls, v: int | None) -> int | None:
        if v is not None and not (MIN_BIRTH_YEAR <= v <= MAX_BIRTH_YEAR):
            raise ValueError(
                f"est_birth_year must be between {MIN_BIRTH_YEAR} and {MAX_BIRTH_YEAR}, got {v}"
            )
        return v

    @field_validator("grad_year")
    @classmethod
    def validate_grad_year(cls, v: int | None) -> int | None:
        if v is not None and not (1950 <= v <= MAX_FOUNDING_YEAR):
            raise ValueError(
                f"grad_year must be between 1950 and {MAX_FOUNDING_YEAR}, got {v}"
            )
        return v

    @field_validator("domain_exp_years")
    @classmethod
    def validate_domain_exp_years(cls, v: int | None) -> int | None:
        if v is not None and not (0 <= v <= 60):
            raise ValueError("domain_exp_years must be between 0 and 60")
        return v

    @field_validator("age_at_founding", "current_age_2026")
    @classmethod
    def validate_ages(cls, v: int | None) -> int | None:
        if v is not None and not (0 <= v <= 100):
            raise ValueError("age values must be between 0 and 100")
        return v


# ---------------------------------------------------------------------------
# InvestmentRecord
# ---------------------------------------------------------------------------


class InvestmentRecord(BaseModel):
    """Maps to the `investments` junction table."""

    id: str | None = None                              # UUID, generated by DB
    vc_id: str = Field(..., description="UUID of the vc_firms row")
    company_id: str = Field(..., description="UUID of the portfolio_companies row")
    stage: str | None = None                          # Investment stage at time
    lead_investor: bool = False
    announced_date: date | None = None
    source_url: str | None = None
    created_at: datetime | None = None


# ---------------------------------------------------------------------------
# FounderAgeResult
# ---------------------------------------------------------------------------


class FounderAgeResult(BaseModel):
    """Result from the triangulator — age estimation for a single founder.

    Returned by triangulate_founder_age() in triangulator.py.
    """

    founder_name: str
    company_name: str
    est_birth_year: int | None = None
    age_at_founding: int | None = None
    current_age_2026: int | None = None
    age_confidence: AgeConfidence = "Low"
    age_inference_method: str | None = None
    reasoning: str | None = Field(
        None,
        description="Claude's step-by-step reasoning for the age estimate",
    )
    sources_used: list[str] = Field(
        default_factory=list,
        description="List of evidence types used (e.g. 'graduation year', 'LinkedIn')",
    )
    raw_response: str | None = Field(
        None,
        description="Raw text response from Claude for audit purposes",
        exclude=True,
    )

    @field_validator("est_birth_year")
    @classmethod
    def validate_birth_year(cls, v: int | None) -> int | None:
        if v is not None and not (MIN_BIRTH_YEAR <= v <= MAX_BIRTH_YEAR):
            raise ValueError(
                f"est_birth_year must be between {MIN_BIRTH_YEAR} and {MAX_BIRTH_YEAR}, got {v}"
            )
        return v

    @model_validator(mode="after")
    def compute_derived_ages(self) -> "FounderAgeResult":
        """Auto-compute current_age_2026 from est_birth_year if not set."""
        if self.est_birth_year is not None and self.current_age_2026 is None:
            self.current_age_2026 = 2026 - self.est_birth_year
        return self


# ---------------------------------------------------------------------------
# PortfolioCompany (lightweight extraction result)
# ---------------------------------------------------------------------------


class PortfolioCompany(BaseModel):
    """Lightweight company record returned from HTML extraction.

    Subset of CompanyRecord — used during pipeline ingestion before
    database UUIDs are assigned.
    """

    name: str = Field(..., min_length=1)
    slug: str = Field(..., min_length=1)
    sector: str | None = None
    subsector: str | None = None
    description: str | None = None
    website: str | None = None
    founded_year: int | None = None
    city: str | None = None
    country: str | None = None
    stage: CompanyStage | None = None
    status: CompanyStatus = "Active"
    status_detail: str | None = None
    source_url: str | None = None
    founders: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Raw founder dicts from extraction (name + role only)",
    )

    @field_validator("founded_year")
    @classmethod
    def validate_founded_year(cls, v: int | None) -> int | None:
        if v is not None and not (MIN_FOUNDING_YEAR <= v <= MAX_FOUNDING_YEAR):
            raise ValueError(
                f"founded_year must be between {MIN_FOUNDING_YEAR} and {MAX_FOUNDING_YEAR}, got {v}"
            )
        return v

    def to_company_record(self) -> CompanyRecord:
        """Promote to a full CompanyRecord (without id/timestamps)."""
        return CompanyRecord(
            name=self.name,
            slug=self.slug,
            sector=self.sector,
            subsector=self.subsector,
            description=self.description,
            website=self.website,
            founded_year=self.founded_year,
            city=self.city,
            country=self.country,
            stage=self.stage,
            status=self.status,
            status_detail=self.status_detail,
            source_url=self.source_url,
        )


# ---------------------------------------------------------------------------
# PortfolioExtractionResult
# ---------------------------------------------------------------------------


class PortfolioExtractionResult(BaseModel):
    """Top-level result from a single pipeline run against one VC firm."""

    vc_slug: str
    vc_name: str
    source_url: str
    companies: list[PortfolioCompany] = Field(default_factory=list)
    companies_found: int = 0
    errors: list[str] = Field(default_factory=list)
    tokens_used: int = 0
    cost_usd: float = 0.0
    model_used: str = ""

    @model_validator(mode="after")
    def sync_companies_found(self) -> "PortfolioExtractionResult":
        """Keep companies_found in sync with the actual companies list."""
        if self.companies_found == 0 and self.companies:
            self.companies_found = len(self.companies)
        return self
